{
 "title": "Moosefs Overview",
 "description": "Use the mfscli command to generate monitoring metrics that can be recognized by prometheus.",
 "tags": [
  "prometheus",
  "moosefs",
  "mfscli"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(moosefs_active_quotas_current_inodes, job)"
    }
   },
   {
    "name": "instance",
    "label": "IP",
    "query": {
     "query": "label_values(moosefs_active_quotas_current_inodes{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "path",
    "label": "PATH",
    "query": {
     "query": "label_values(moosefs_active_quotas_current_inodes{job=~\"$job\",instance=~\"$instance\"},path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "moosefs master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "avail space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_avail_space{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "total space",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "moosefs_master_info_total_space{job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "cpu used user",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_cpu_used_user{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "cpu used system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_cpu_used_system{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "ram used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_ram_used{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "free space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_free_space{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "trash space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_trash_space{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "trash files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_trash_files{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "sustained space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_sustained_space{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "sustained files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_sustained_files{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "all fs objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_all_fs_objects{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "directories",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_directories{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_files{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "chunks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_chunks{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "all chunk copies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_all_chunk_copies{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "regular chunk copies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_regular_chunk_copies{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "last successful store",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_last_successful_store{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "last save duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "moosefs_master_info_last_save_duration{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "moosefs metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "metadata version",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_metadata_servers_metadata_version{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "ram used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "moosefs_metadata_servers_ram_used{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "cpu used all",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "moosefs_metadata_servers_cpu_used_all{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "cpu used sys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "moosefs_metadata_servers_cpu_used_sys{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "cpu used user",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "moosefs_metadata_servers_cpu_used_user{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "last meta save",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_metadata_servers_last_meta_save{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "last save duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "moosefs_metadata_servers_last_save_duration{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "last saved in background",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "moosefs_metadata_servers_last_saved_in_background{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "moosefs chunk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_chunk_servers_load{job=~\"$job\"}",
       "legendFormat": "{{all}}"
      }
     ]
    },
    {
     "title": "regular hdd space used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "moosefs_chunk_servers_regular_hdd_space_used{job=~\"$job\"}",
       "legendFormat": "{{all}}"
      }
     ]
    },
    {
     "title": "regular hdd space chunks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "moosefs_chunk_servers_regular_hdd_space_chunks{job=~\"$job\"}",
       "legendFormat": "{{all}}"
      }
     ]
    },
    {
     "title": "regular hdd space total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "moosefs_chunk_servers_regular_hdd_space_total{job=~\"$job\"}",
       "legendFormat": "{{all}}"
      }
     ]
    }
   ]
  },
  {
   "title": "moosefs quotas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "quotas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "moosefs_active_quotas_current_size{job=~\"$job\",path=~\"$path\"} / moosefs_active_quotas_soft_size{job=~\"$job\",path=~\"$path\"}",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  }
 ]
}