name: Renovate

on:
    schedule:
        - cron: "0 19 * * *"
    workflow_dispatch:
    pull_request:
        types: [opened]

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@0b17c4eb901eca44d018fb25744a50a74b2042df # v46.1.4
              with:
                  configurationFile: renovate.json
                  token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
              env:
                  LOG_LEVEL: debug
                  RENOVATE_REPOSITORIES: ${{ github.repository }}

    notify:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/')
        steps:
            - name: Send Slack Notification
              run: |
                  MESSAGE="*[ Renovate Update ]*\n\n*Repository:* ${{ github.repository }}\n*PR Created:* ${{ github.event.pull_request.title }}\n\n<${{ github.event.pull_request.html_url }}|View PR>"

                  curl -s -X POST -H 'Content-type: application/json' \
                    --data "{\"text\": \"$MESSAGE\"}" \
                    $SLACK_WEBHOOK_URL
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
