name: Renovate

on:
    schedule:
        - cron: "0 19 * * *"
    workflow_dispatch:
    pull_request:
        types: [opened]

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@8d75b92f43899d483728e9a8a7fd44238020f6e6 # v46.1.2
              with:
                  configurationFile: renovate.json
                  token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
              env:
                  LOG_LEVEL: debug
                  RENOVATE_REPOSITORIES: ${{ github.repository }}

    notify:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/')
        steps:
            - name: Send Telegram Notification
              run: |
                  MESSAGE=$(cat << 'EOF'
                  <b>[ Renovate Update ]</b>

                  <b>Repository:</b> ${{ github.repository }}
                  <b>PR Created:</b> ${{ github.event.pull_request.title }}

                  <a href="${{ github.event.pull_request.html_url }}">View PR</a>
                  EOF
                  )
                  curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
                    -d chat_id="$TELEGRAM_CHAT_ID" \
                    --data-urlencode "text=${MESSAGE}" \
                    -d parse_mode="HTML"
              env:
                  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
