name: Renovate

on:
    schedule:
        - cron: "0 19 * * *"
    workflow_dispatch:
    pull_request:
        types: [opened]

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@d65ef9e20512193cc070238b49c3873a361cd50c # v46.1.1
              with:
                  configurationFile: renovate.json
                  token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
              env:
                  LOG_LEVEL: debug
                  RENOVATE_REPOSITORIES: ${{ github.repository }}

    notify:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/')
        steps:
            - name: Send Telegram Notification
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_CHAT_ID }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      📦 Renovate Update

                      PR Created: ${{ github.event.pull_request.title }}
                      repository: ${{ github.repository }}

                      [View PR](${{ github.event.pull_request.html_url }})
